framework:
    messenger:

        failure_transport: failed

        transports:
            amqp_order_bus:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: order_messages
                        type: fanout
                    queues:
                        order_messages: ~
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2

            amqp_email_notification:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: email_notifications
                        type: fanout
                    queues:
                        email_notifications: ~
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2

            amqp_telegram_notification:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: telegram_notifications
                        type: fanout
                    queues:
                        telegram_notifications: ~
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2

            failed: 'doctrine://default?queue_name=failed'

            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: amqp_email_notification
            Symfony\Component\Notifier\Message\ChatMessage: amqp_telegram_notification

            App\Message\OrderMessage: amqp_order_bus
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
