vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        product_image:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false # default false, should the file be injected into the uploadable entity when it is loaded from the data store. The object will be an instance of Symfony\Component\HttpFoundation\File\File
            delete_on_update: true # default true, should the file be deleted when a new file is uploaded
            delete_on_remove: false # default true, should the file be deleted when the entity is removed

        customer_document:
            uri_prefix: /documents/customers
            upload_destination: '%kernel.project_dir%/public/documents/customers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false
